coverage:
  status:
    project:
      default:
        target: 94%
        threshold: 1%
    patch:
      default:
        target: 85%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
